/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DbImport } from './routes/db'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DbRoute = DbImport.update({
  path: '/db',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/db': {
      id: '/db'
      path: '/db'
      fullPath: '/db'
      preLoaderRoute: typeof DbImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, DbRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/db"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/db": {
      "filePath": "db.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
